"""empty message

Revision ID: 7d952ab34f8e
Revises: b0f208bfc051
Create Date: 2021-06-15 13:18:52.714294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d952ab34f8e'
down_revision = 'b0f208bfc051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_kyc_veried', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_kyc_veried')
    # ### end Alembic commands ###
