"""empty message

Revision ID: 92bdc260a574
Revises: 97e736b09749
Create Date: 2021-06-15 10:20:24.007963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92bdc260a574'
down_revision = '97e736b09749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('dob', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    # ### end Alembic commands ###
