"""empty message

Revision ID: b0f208bfc051
Revises: 92bdc260a574
Create Date: 2021-06-15 11:25:16.357542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f208bfc051'
down_revision = '92bdc260a574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_kyc_veried')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_kyc_veried', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
